FROM lgatica/node-krb5:latest

# NPM dependencies (cache)
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/

ADD . /opt/app
WORKDIR /opt/app

EXPOSE 3000

CMD ["npm", "run", "dev"]
